[package]
name = "optimizer"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
itertools = "0.13.0"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
tetris = { path = "../tetris" }
bot= { path = "../bot" }
