[package]
name = "optimizer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
tetris = { path = "../tetris" }
bot= { path = "../bot" }
